import {
    FaAnchor,
    FaAppleAlt,
    FaBaseballBall,
    FaBasketballBall,
    FaBicycle,
    FaBinoculars,
    FaBirthdayCake,
    FaBone,
    FaBolt,
    FaBomb,
    FaBowlingBall,
    FaBug,
    FaBreadSlice,
    FaCandyCane,
    FaCarrot,
    FaCat,
    FaChessBishop,
    FaChessKing,
    FaChessKnight,
    FaChessPawn,
    FaChessQueen,
    FaChessRook,
    FaCoffee,
    FaCrow,
    FaDharmachakra,
    FaDog,
    FaDove,
    FaDragon,
    FaEnvira,
    FaFeather,
    FaFireAlt,
    FaFish,
    FaFootballBall,
    FaFrog,
    FaFutbol,
    FaGem,
    FaGhost,
    FaGlassMartiniAlt,
    FaGrav,
    FaGuitar,
    FaHamburger,
    FaHatWizard,
    FaHorseHead,
    FaHippo,
    FaHiking,
    FaHotdog,
    FaHotjar,
    FaIceCream,
    FaItunesNote,
    FaKiwiBird,
    FaLemon,
    FaLeaf,
    FaMagic,
    FaMarker,
    FaMeteor,
    FaMoon,
    FaMountain,
    FaPalette,
    FaPaw,
    FaPenFancy,
    FaPepperHot,
    FaRegPaperPlane,
    FaRegSnowflake,
    FaRegStar,
    FaRegSun,
    FaRing,
    FaRocket,
    FaSeedling,
    FaSkull,
    FaSuse,
    FaUmbrella,
    FaWineGlassAlt,
    FaYinYang,
} from "react-icons/fa";

export const userIcons = [
    {icon: FaAnchor, id: 'anchor'},
    {icon: FaAppleAlt, id: 'apple'},
    {icon: FaBaseballBall, id: 'baseball'},
    {icon: FaBasketballBall, id: 'basketball'},
    {icon: FaBicycle, id: 'bicycle'},
    {icon: FaBinoculars, id: 'binoculars'},
    {icon: FaBirthdayCake, id: 'birthdayCake'},
    {icon: FaBone, id: 'bone'},
    {icon: FaBolt, id: 'bolt'},
    {icon: FaBomb, id: 'bomb'},
    {icon: FaBowlingBall, id: 'bowling'},
    {icon: FaBug, id: 'bug'},
    {icon: FaBreadSlice, id: 'bread'},
    {icon: FaCandyCane, id: 'candyCane'},
    {icon: FaCarrot, id: 'carrot'},
    {icon: FaCat, id: 'cat'},
    {icon: FaChessBishop, id: 'bishop'},
    {icon: FaChessKing, id: 'king'},
    {icon: FaChessKnight, id: 'knight'},
    {icon: FaChessPawn, id: 'pawn'},
    {icon: FaChessQueen, id: 'queen'},
    {icon: FaChessRook, id: 'rook'},
    {icon: FaCoffee, id: 'coffee'},
    {icon: FaCrow, id: 'crow'},
    {icon: FaDharmachakra, id: 'dharmaChakra'},
    {icon: FaDog, id: 'dog'},
    {icon: FaDove, id: 'dove'},
    {icon: FaDragon, id: 'dragon'},
    {icon: FaEnvira, id: 'envira'},
    {icon: FaFeather, id: 'feather'},
    {icon: FaFireAlt, id: 'fireAlt'},
    {icon: FaFish, id: 'fish'},
    {icon: FaFootballBall, id: 'football'},
    {icon: FaFrog, id: 'frog'},
    {icon: FaFutbol, id: 'futbol'},
    {icon: FaGem, id: 'gem'},
    {icon: FaGhost, id: 'ghost'},
    {icon: FaGlassMartiniAlt, id: 'martini'},
    {icon: FaGrav, id: 'grav'},
    {icon: FaGuitar, id: 'guitar'},
    {icon: FaHamburger, id: 'hamburger'},
    {icon: FaHatWizard, id: 'wizardHat'},
    {icon: FaHorseHead, id: 'horseHead'},
    {icon: FaHippo, id: 'hippo'},
    {icon: FaHiking, id: 'hiking'},
    {icon: FaHotdog, id: 'hotdog'},
    {icon: FaHotjar, id: 'hotJar'},
    {icon: FaIceCream, id: 'icecream'},
    {icon: FaItunesNote, id: 'tunesNote'},
    {icon: FaKiwiBird, id: 'kiwi'},
    {icon: FaLemon, id: 'lemon'},
    {icon: FaLeaf, id: 'leaf'},
    {icon: FaMagic, id: 'magic'},
    {icon: FaMarker, id: 'marker'},
    {icon: FaMeteor, id: 'meteor'},
    {icon: FaMoon, id: 'moon'},
    {icon: FaMountain, id: 'mountain'},
    {icon: FaPalette, id: 'palette'},
    {icon: FaPaw, id: 'paw'},
    {icon: FaPenFancy, id: 'penFancy'},
    {icon: FaPepperHot, id: 'pepperHot'},
    {icon: FaRegPaperPlane, id: 'paperPlane'},
    {icon: FaRegSnowflake, id: 'snowflake'},
    {icon: FaRegStar, id: 'regStar'},
    {icon: FaRegSun, id: 'regSun'},
    {icon: FaRing, id: 'ring'},
    {icon: FaRocket, id: 'rocket'},
    {icon: FaSeedling, id: 'seedling'},
    {icon: FaSkull, id: 'skull'},
    {icon: FaSuse, id: 'suse'},
    {icon: FaUmbrella, id: 'umbrella'},
    {icon: FaWineGlassAlt, id: 'wine'},
    {icon: FaYinYang, id: 'yinyang'},
];

export const userIconColor = [
    {hexcode: '#f5f5f5', id:'#f5f5f5'},
    {hexcode: '#aec78d', id:'#aec78d'},
    {hexcode: '#74c3b0', id:'#74c3b0'},
    {hexcode: '#b9e3d7', id:'#b9e3d7'},
    {hexcode: '#c8eafe', id:'#c8eafe'},
    {hexcode: '#9dd6ff', id:'#9dd6ff'},
    {hexcode: '#869bd2', id:'#869bd2'},
    {hexcode: '#7eced3', id:'#7eced3'},
    {hexcode: '#d8aed6', id:'#d8aed6'},
    {hexcode: '#ffccd9', id:'#ffccd9'},
    {hexcode: '#fe8faf', id:'#fe8faf'},
    {hexcode: '#f18581', id:'#f18581'},
    {hexcode: '#ffeaab', id:'#ffeaab'},
    {hexcode: '#ffd07e', id:'#ffd07e'},
    {hexcode: '#ffa884', id:'#ffa884'},
];